### ISSUE TITLE
点击删除出现报错 = = 

### ISSUE THREAD

**Issue by yanhuanyu** [shellus/SiteMonitor#6]
大佬 = = 点删除项目的时候 出现错误 是不是有升级好的代码

**Comment by shellus** [comment]
请贴出报错信息

**Comment by yanhuanyu** [comment]
感谢大佬回复 ，图示这样的 
![image](https://user-images.githubusercontent.com/37525283/87106319-c5087880-c28f-11ea-838d-3e1070302962.png)

**Comment by shellus** [comment]
报错信息显示删除快照文件夹失败，我感觉可能是因为快照文件夹从未写入，所以还没有这个文件夹

现在你可以编辑这个文件，注释掉第45行即可

如果你懂php的话，可以给此处增加一个文件夹是否存在的判断，如果存在才去删除
